# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d17ae4752a44cb29ffd4cad861cb1365"
name = "time-clock-app"
application_url = "<SHOPIFY_APP_URL>"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "<SHOPIFY_APP_URL>/api/auth" ]
